spring:
  application:
    name: affismart-mall-be
  profiles:
    default: dev
  mvc:
    problemdetails:
      enabled: false
  jackson:
    time-zone: Asia/Bangkok

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

app:
  timezone: Asia/Bangkok
  cors:
    allow-credentials: true
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
